---
- name: webserver setup
  hosts: webserver
  become: yes
  tasks:
    - name: copy config file
      copy:
        src: /home/synnefo/ansible-project/files/apache2.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart apache2

  handlers:
    - name: restart apache2
      service:
       name : apache2
       state: restarted
