---
- name: Set the root password for MariaDB
  hosts: databaseserver  
  become: yes  
  tasks:

    - name: Secure MariaDB Installation by setting the root password
      mysql_user:
        name: root
        password: "root"
        host: "localhost"
        state: present

