---
- name: User management playbook
  hosts: webserver1
  become: yes

  tasks:
    - name: create user ansible2
      user:
        name: ansible2
        state: present
        shell: /bin/bash
      tags: 
       - create_user

    - name: Delete user ansible2
      user:
        name: ansible2
        state: absent
      tags:
        - delete_user
